src/Entity/Author.php
<?php

namespace App\Entity;

use App\Repository\AuthorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: AuthorRepository::class)]
#[UniqueEntity(
    fields: ['first_name', 'middle_name', 'last_name'],
    message: 'The author with this combination of first, middle and last name already exists.',
    errorPath: 'first_name',
)]
class Author
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $middle_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\ManyToMany(targetEntity: Book::class, mappedBy: 'authors')]
    private Collection $books;

    public function __construct()
    {
        $this->books = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getMiddleName(): ?string
    {
        return $this->middle_name;
    }

    public function setMiddleName(string $middle_name): static
    {
        $this->middle_name = $middle_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    /**
     * @return Collection<int, Book>
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): static
    {
        if (!$this->books->contains($book)) {
            $this->books->add($book);
            $book->addAuthor($this);
        }

        return $this;
    }

    public function removeBook(Book $book): static
    {
        if ($this->books->removeElement($book)) {
            $book->removeAuthor($this);
        }

        return $this;
    }

    public function __toString(): string
    {
        return implode(' ', [$this->first_name, $this->middle_name, $this->last_name]);
    }
}

src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: BookRepository::class)]
#[UniqueEntity(
    fields: ['name', 'isbn'],
    message: 'The book with this combination of name and ISBN already exists.',
    errorPath: 'name',
)]
#[UniqueEntity(
    fields: ['publication_year', 'isbn'],
    message: 'The book with this combination of publication year and ISBN already exists.',
    errorPath: 'publication_year',
)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $publication_year = null;

    #[ORM\Column(length: 255)]
    #[Assert\Isbn]
    private ?string $isbn = null;

    #[ORM\Column]
    private ?int $pages_count = null;

    #[ORM\ManyToMany(targetEntity: Author::class, inversedBy: 'books')]
    #[Assert\Count(min: 1, minMessage: "You must specify at least one author.")]
    private Collection $authors;

    public function __construct()
    {
        $this->authors = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPublicationYear(): ?int
    {
        return $this->publication_year;
    }

    public function setPublicationYear(int $publication_year): static
    {
        $this->publication_year = $publication_year;

        return $this;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): static
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getPagesCount(): ?int
    {
        return $this->pages_count;
    }

    public function setPagesCount(int $pages_count): static
    {
        $this->pages_count = $pages_count;

        return $this;
    }

    /**
     * @return Collection<int, Author>
     */
    public function getAuthors(): Collection
    {
        return $this->authors;
    }

    public function addAuthor(Author $author): static
    {
        if (!$this->authors->contains($author)) {
            $this->authors->add($author);
        }

        return $this;
    }

    public function removeAuthor(Author $author): static
    {
        $this->authors->removeElement($author);

        return $this;
    }

    public function __toString() {
        return $this->name;
    }
}

src/Form/Type/AuthorType.php
<?php

namespace App\Form\Type;

use App\Entity\Author;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AuthorType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Author::class,
            'submit' => 'Create author'
        ]);
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('first_name', TextType::class)
            ->add('middle_name', TextType::class)
            ->add('last_name', TextType::class)
            ->add('save', SubmitType::class, ['label' => $options['submit']])
        ;
    }
}

src/Controller/AuthorController.php
<?php

namespace App\Controller;

use App\Entity\Author;
use App\Form\Type\AuthorType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AuthorController extends BaseController
{
    #[Route('/author/create', name: 'author_create')]
    public function create(EntityManagerInterface $entityManager, Request $request): Response {

        $author = new Author();
        $form = $this->createForm(AuthorType::class, $author, ['submit' => 'Create author']);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $author = $form->getData();
            $entityManager->persist($author);
            $entityManager->flush();
            return $this->redirectToRoute('author_index');
        }

        return $this->render('author/create.html.twig', [
            'form' => $form
        ]);
    }

    #[Route('/author/update/{id}', name: 'author_update')]
    public function update(EntityManagerInterface $entityManager, Request $request, int $id): Response {

        $author = $this->findModel($entityManager, $id, Author::class);
        $form = $this->createForm(AuthorType::class, $author, ['submit' => 'Update author']);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $author = $form->getData();
            $entityManager->persist($author);
            $entityManager->flush();
            return $this->redirectToRoute('author_index');
        }

        return $this->render('author/update.html.twig', [
            'form' => $form,
            'author' => $author
        ]);
    }

    #[Route('/author/delete/{id}', name: 'author_delete')]
    public function delete(EntityManagerInterface $entityManager, int $id): Response {

        $author = $this->findModel($entityManager, $id, Author::class);
        $entityManager->remove($author);
        $entityManager->flush();

        return $this->redirectToRoute('author_index');
    }

    #[Route('/author/index', name: 'author_index')]
    public function index(EntityManagerInterface $entityManager): Response {

        $authors = $entityManager
            ->getRepository(Author::class)
            ->findAll();

        return $this->render('author/index.html.twig', [
            'authors' => $authors
        ]);
    }

    #[Route('/author/view/{id}', name: 'author_view')]
    public function view(EntityManagerInterface $entityManager, int $id): Response {

        $author = $this->findModel($entityManager, $id, Author::class);

        return $this->render('author/view.html.twig', [
            'author' => $author
        ]);
    }

}

templates/author/_form.html.twig
{{ form(form) }}

templates/author/create.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<h1>Create book</h1>
<a href="{{ path('author_index') }}">
    Back
</a>
{{ include('author/_form.html.twig', {form: form}) }}
{% endblock %}

templates/author/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>All authors</h1>
    <a href="{{ path('author_create') }}">
        New author
    </a>
    {% if authors is not empty %}
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th colspan="3">Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for author in authors %}
                <tr>
                    <td>{{ author }}</td>
                    <td>
                        <a href="{{ path('author_view', {id: author.id}) }}">
                            View
                        </a>
                    </td>
                    <td>
                        <a href="{{ path('author_update', {id: author.id}) }}">
                            Update
                        </a>
                    </td>
                    <td>
                        <a href="{{ path('author_delete', {id: author.id}) }}">
                            Delete
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <br>
        <span>No results found.</span>
    {% endif %}
{% endblock %}

templates/author/update.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<h1>Update author {{ author }}</h1>
<a href="{{ path('author_index') }}">
    Back
</a>
{{ include('author/_form.html.twig', {form: form}) }}
{% endblock %}

templates/author/view.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>View author {{ author }}</h1>
    <a href="{{ path('author_index') }}">
        Back
    </a>
    <br>
    <table>
        <tbody>
            <tr>
                <td>Middle name</td>
                <td>{{ author.middleName }}</td>
            </tr>
            <tr>
                <td>First name</td>
                <td>{{ author.firstName }}</td>
            </tr>
            <tr>
                <td>Last name</td>
                <td>{{ author.lastName }}</td>
            </tr>
        </tbody>
    </table>
    <h2>Books:</h2>
    {% if author.books is not empty %}
        <table>
            <thead>
            <tr>
                <th>Name</th>
                <th>Publication year</th>
                <th>ISBN</th>
                <th>Pages count</th>
                <th colspan="2">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for book in author.books %}
                <tr>
                    <td>{{ book }}</td>
                    <td>{{ book.publicationYear }}</td>
                    <td>{{ book.isbn }}</td>
                    <td>{{ book.pagesCount }}</td>
                    <td>
                        <a href="{{ path('book_view', {id: book.id}) }}">
                            View
                        </a>
                    </td>
                    <td>
                        <a href="{{ path('book_update', {id: book.id}) }}">
                            Update
                        </a>
                    </td>
                    <td>
                        <a href="{{ path('book_delete', {id: book.id}) }}">
                            Delete
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <span>No results found</span>
    {% endif %}
{% endblock %}